# Generated by Django 5.0.4 on 2024-06-11 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dowloandvideo',
            name='file',
            field=models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'WMV', 'png'])]),
        ),
    ]
